import PptxGenJS from "pptxgenjs";
import type { SlideContent } from "./content-schema";
import { applyGradients } from "./pptx-gradient";
import { addContentSlide, applyTemplateLayout } from "./pptx";
import { SLIDE_TEMPLATE } from "./template";
import type { SlideTemplate } from "./template";

// ============================================
// The generated PowerPoint artifact
//
// The lesson renderer is deliberately downstream of this file. The agent
// authors a complete deck, this module writes the actual .pptx, and only then
// does the import pipeline translate that artifact into browser HTML.
// ============================================

export interface DeckArtifact {
  buffer: Buffer;
  warnings: string[];
}

export async function buildDeckArtifact(
  title: string,
  contents: SlideContent[],
  template: SlideTemplate = SLIDE_TEMPLATE,
): Promise<DeckArtifact> {
  if (contents.length === 0) throw new Error("Cannot build an empty PowerPoint deck.");

  const pptx = new PptxGenJS();
  applyTemplateLayout(pptx, template);
  pptx.author = "Ecotech LMS";
  pptx.title = title;
  pptx.subject = `Generated by Ecotech LMS: ${title}`;

  const warnings: string[] = [];
  for (const [index, content] of contents.entries()) {
    const added = addContentSlide(pptx, content, template, {
      slideNumber: index + 1,
    });
    warnings.push(...added.warnings.map((warning) => `slide ${index + 1}: ${warning}`));
  }

  const written = (await pptx.write({ outputType: "nodebuffer" })) as Buffer;
  const buffer = await applyGradients(written, template);
  return { buffer, warnings };
}
